export const Action = {
    UP: "UP",
    DOWN: "DOWN",
    LEFT: "LEFT",
    RIGHT: "RIGHT",
    ENTER: "ENTER",
    MENU_OVERFLOW: "MENU_OVERFLOW",
    INIT: "INIT",
    ESCAPE: "ESCAPE",
    RESET: "RESET",
    ADD_BLAST: "ADD_BLAST",
    BLAST_VANISHED: "BLAST_VANISHED",
    DROP_BOMB: "DROP_BOMB",
    BOMB_EXPLODED: "BOMB_EXPLODED",
    DESTROY: "DESTROY",
    KILL: "KILL",
    VICTORY: "VICTORY",
    CONNECT: "CONNECT",
    INIT_CHARACTERS: "INIT_CHARACTERS",
    PLAYER_CHOSEN: "PLAYER_CHOSEN",
    CHANGE_GAME_STATUS: "CHANGE_GAME_STATUS",
    MOVE: "MOVE",
    ADD_BOMB: "ADD_BOMB",
    CONSUME_BONUS: "CONSUME_BONUS",
    GET_BONUS: "GET_BONUS"

};

Object.freeze(Action);
