export const Action = {
    UP: "UP",
    DOWN: "DOWN",
    LEFT: "LEFT",
    RIGHT: "RIGHT",
    ENTER: "ENTER",
    ADD_PLAYER : "ADD_PLAYER",
    MENU_OVERFLOW: "MENU_OVERFLOW",
    ESCAPE: "ESCAPE",
    RESET: "RESET",
    ADD_BLAST: "ADD_BLAST",
    BLAST_VANISHED: "BLAST_VANISHED",
    DROP_BOMB: "DROP_BOMB",
    BOMB_EXPLODED: "BOMB_EXPLODED",
    DESTROY: "DESTROY",
    KILL: "KILL",
    VICTORY: "VICTORY",
    INIT_GAME: "INIT_GAME",
    CONSUME_BONUS: "CONSUME_BONUS",
    GET_BONUS: "GET_BONUS",
    MOVE: "MOVE",
    BONUS_EXPLODED: "BONUS_EXPLODED"

};

Object.freeze(Action);
